<?php

/**
 * Class FUE_Addon_Woocommerce_Reports
 */
class FUE_Addon_Woocommerce_Reports {
    
    public function __construct() {
        $this->register_hooks();
    }
    
    private function register_hooks() {
        // Reports
        add_action( 'fue_reports_section_list', array($this, 'report_section_list') );
        add_action( 'fue_reports_section_div', array($this, 'report_section_div') );
        add_filter( 'fue_report_email_trigger', array($this, 'report_email_trigger'), 10, 2 );

        add_filter( 'fue_report_email_address', array($this, 'report_email_address'), 10, 2 );
        add_filter( 'fue_report_order_str', array($this, 'report_order_str'), 10, 2 );

        add_action( 'fue_reports_reset', array($this, 'reset_reports') );
    }

    public function report_section_list() {
        echo '<li>| <a href="#coupons">'. __('Coupons', 'follow_up_emails') .'</a></li>';
    }

    public function report_section_div() {
        // coupons sorting
        $sort['sortby'] = 'date_sent';
        $sort['sort']   = 'desc';

        if ( isset($_GET['sortby']) && !empty($_GET['sortby']) ) {
            $valid = array('date_sent', 'email_address', 'coupon_used');
            if ( in_array($_GET['sortby'], $valid) ) {
                $sort['sortby'] = $_GET['sortby'];
                $sort['sort']   = (isset($_GET['sort']) && $_GET['sort'] == 'asc') ? 'asc' : 'desc';
            }
        }

        $coupon_reports = FUE_Reports::get_reports(array('type' => 'coupons', 'sort' => $sort));

        $email_address_class    = ($sort['sortby'] != 'email_address') ? 'sortable' : 'sorted';
        $email_address_sort     = ($email_address_class == 'sorted') ? $sort['sort'] : 'asc';
        $email_address_dir      = ($email_address_sort == 'asc') ? 'desc' : 'asc';

        $used_class     = ($sort['sortby'] != 'coupon_used') ? 'sortable' : 'sorted';
        $used_sort      = ($used_class == 'sorted') ? $sort['sort'] : 'asc';
        $used_dir       = ($used_sort == 'asc') ? 'desc' : 'asc';

        $sent_class     = ($sort['sortby'] != 'date_sent') ? 'sortable' : 'sorted';
        $sent_sort      = ($sent_class == 'sorted') ? $sort['sort'] : 'asc';
        $sent_dir       = ($sent_sort == 'asc') ? 'desc' : 'asc';

        ?>
        <div class="section" id="coupons">
            <h3><?php _e('Coupons', 'follow_up_emails'); ?></h3>
            <form action="admin-post.php" method="post">
                <table class="wp-list-table widefat fixed posts">
                    <thead>
                    <tr>
                        <th scope="col" id="cb" class="manage-column column-cb check-column">
                            <label class="screen-reader-text" for="cb-select-all-coupons">Select All</label>
                            <input id="cb-select-all-coupons" type="checkbox">
                        </th>
                        <th scope="col" id="coupon_name" class="manage-column column-type" style=""><?php _e('Coupon Name', 'follow_up_emails'); ?></th>
                        <th scope="col" id="email_address" class="manage-column column-usage_count <?php echo $email_address_class .' '. $email_address_sort; ?>" style="">
                            <a href="admin.php?page=followup-emails-reports&tab=reports&sortby=email_address&sort=<?php echo $email_address_dir; ?>&v=coupons">
                                <span><?php _e('Email Address', 'follow_up_emails'); ?></span>
                                <span class="sorting-indicator"></span>
                            </a>
                        </th>
                        <th scope="col" id="coupon_code" class="manage-column column-usage_count" style=""><?php _e('Coupon Code', 'follow_up_emails'); ?> <img class="help_tip" width="16" height="16" title="<?php _e('This is the unique coupon code generated by the follow-up email for this specific email address', 'follow_up_emails'); ?>" src="<?php echo FUE_TEMPLATES_URL; ?>/images/help.png" /></th>
                        <th scope="col" id="email_name" class="manage-column column-usage_count" style=""><?php _e('Email Name', 'follow_up_emails'); ?> <img class="help_tip" width="16" height="16" title="<?php _e('This is the name of the follow-up email that generated the coupon that was sent to this specific email address', 'follow_up_emails'); ?>" src="<?php echo FUE_TEMPLATES_URL; ?>/images/help.png" /></th>
                        <th scope="col" id="used" class="manage-column column-used <?php echo $used_class .' '. $used_sort; ?>" style="">
                            <a href="admin.php?page=followup-emails-reports&tab=reports&sortby=coupon_used&sort=<?php echo $used_dir; ?>&v=coupons">
                                <span><?php _e('Used', 'follow_up_emails'); ?>  <img class="help_tip" width="16" height="16" title="<?php _e('This tells you if this specific coupon code generated and sent via follow-up emails has been used, and if it has, it includes the date and time', 'follow_up_emails'); ?>" src="<?php echo FUE_TEMPLATES_URL; ?>/images/help.png" /></span>
                                <span class="sorting-indicator"></span>
                            </a>
                        </th>
                        <th scope="col" id="date_sent" class="manage-column column-date_sent <?php echo $sent_class .' '. $sent_sort; ?>" style="">
                            <a href="admin.php?page=followup-emails-reports&tab=reports&sortby=date_sent&sort=<?php echo $sent_dir; ?>&v=coupons">
                                <span><?php _e('Date Sent', 'follow_up_emails'); ?> <img class="help_tip" width="16" height="16" title="<?php _e('This is the date and time that this specific coupon code was sent to this email address', 'follow_up_emails'); ?>" src="<?php echo FUE_TEMPLATES_URL; ?>/images/help.png" /></span>
                                <span class="sorting-indicator"></span>
                            </a>
                        </th>
                    </tr>
                    </thead>
                    <tbody id="the_list">
                    <?php
                    if (empty($coupon_reports)) {
                        echo '
                            <tr scope="row">
                                <th colspan="7">'. __('No reports available', 'follow_up_emails') .'</th>
                            </tr>';
                    } else {
                        foreach ($coupon_reports as $report) {
                            $used = __('No', 'follow_up_emails');

                            if ( $report->coupon_used == 1 ) {
                                $date = date( get_option('date_format') .' '. get_option('time_format') , strtotime($report->date_used));
                                $used = sprintf(__('Yes (%s)', 'follow_up_emails'), $date);
                            }

                            echo '
                                <tr scope="row">
                                    <th scope="row" class="check-column">
                                        <input id="cb-select-'. $report->id .'" type="checkbox" name="coupon_id[]" value="'. $report->id .'">
                                        <div class="locked-indicator"></div>
                                    </th>
                                    <td class="post-title column-title">
                                        <strong>'. stripslashes($report->coupon_name) .'</strong>
                                    </td>
                                    <td>'. esc_html($report->email_address) .'</td>
                                    <td>'. esc_html($report->coupon_code) .'</td>
                                    <td>'. esc_html($report->email_name) .'</td>
                                    <td>'. $used .'</td>
                                    <td>'. date( get_option('date_format') .' '. get_option('time_format') , strtotime($report->date_sent)) .'</td>
                                </tr>
                                ';
                        }
                    }
                    ?>
                    </tbody>
                </table>
                <div class="tablenav bottom">
                    <div class="alignleft actions bulkactions">
                        <input type="hidden" name="action" value="fue_reset_reports" />
                        <input type="hidden" name="type" value="coupons" />
                        <select name="coupons_action">
                            <option value="-1" selected="selected"><?php _e('Bulk Actions', 'wordpress'); ?></option>
                            <option value="trash"><?php _e('Delete Selected', 'follow_up_emails'); ?></option>
                        </select>
                        <input type="submit" name="" id="doaction-coupon" class="button action" value="Apply">
                    </div>
                </div>
            </form>
        </div>
    <?php
    }

    public function report_email_trigger( $trigger, $email_row ) {
        $meta = '';

        if ( isset($email_row->meta) ) {
            $email_meta = maybe_unserialize( $email_row->meta );

            if ( $email_row->interval_type == 'order_total_above' && isset($email_meta['order_total_above']) ) {
                $meta = woocommerce_price($email_meta['order_total_above']);
            } elseif ( $email_row->interval_type == 'order_total_below' && isset($email_meta['order_total_below']) ) {
                $meta = woocommerce_price( $email_meta['order_total_below'] );
            }
        }

        return $trigger .' '. $meta;
    }

    public function report_email_address( $email, $report ) {

        if ( $report->order_id && $report->order_id != 0 ) {
            $order = WC_FUE_Compatibility::wc_get_order($report->order_id);
            $email = $order->billing_email;
        }

        return $email;
    }

    /**
     * Reset coupon logs
     * @param array $data
     */
    public function reset_reports( $data ) {
        $wpdb = Follow_Up_Emails::instance()->wpdb;

        if ( $data['type'] == 'coupons' && $data['coupons_action'] == 'trash' ) {
            $coupon_ids_str = implode(',', $data['coupon_id']);

            /*foreach ( $data['coupon_id'] as $coupon_id ) {
                $wpdb->update( $wpdb->prefix . 'followup_coupons', array('usage_count' => 0), array('id' => $coupon_id) );
            }*/

            $wpdb->query("DELETE FROM {$wpdb->prefix}followup_coupon_logs WHERE id IN ($coupon_ids_str)");
        }
    }

    public static function report_order_str( $str, $report ) {
        if ( $report->order_id != 0 ) {
            $order      = WC_FUE_Compatibility::wc_get_order( $report->order_id );
            $str  = '<a href="'. get_admin_url() .'post.php?post='. $report->order_id .'&action=edit">View Order</a>';
        }

        return $str;
    }
    
}