language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update && composer --version
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
